language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tran827/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tran827/docker-react npm run test